# Generated by Django 4.0.6 on 2022-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=20)),
                ('reputation', models.FloatField(max_length=20)),
            ],
        ),
    ]
