# Generated by Django 4.0.6 on 2022-07-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.TextField()),
                ('img1', models.TextField()),
                ('img2', models.TextField()),
                ('img3', models.TextField()),
                ('img4', models.TextField()),
                ('img_big', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('reputation', models.FloatField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('small_title1', models.CharField(max_length=30)),
                ('small_content1', models.CharField(max_length=500)),
                ('small_title2', models.CharField(max_length=30)),
                ('small_content2', models.CharField(max_length=500)),
                ('recommend_load_img', models.TextField()),
            ],
        ),
    ]
