# Generated by Django 4.0.6 on 2022-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_experience_detail_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.TextField()),
                ('login_password', models.TextField()),
            ],
        ),
    ]
